theme: jekyll-theme-cayman
title: Get it done
description: "Are notes when coding, research,... classified by topics to search, review when needed, and share.<br/>
Click a topic to explorer, get it and done."
show_downloads: true
github:
  is_project_page: true
  repository_url: https://github.com/nnthuan/nnthuan.github.io
