theme: jekyll-theme-cayman
title: Get it done
description: "Are notes when coding, research,... classified by topics to search, review when needed, and share.<br/>Click a topic to explorer, get it and done."
